services:

    ollama:
        container_name: ollama
        build: .
        # devices:
        #     - /dev/dri
        #     - /dev/kfd
        environment:
            - DELETE_MODELS=true
            - OLLAMA_DEBUG=1
            - PRELOAD_MODELS=gemma3:1b
            - PULL_MODELS=llama3.2:1b
        volumes:
            - "./data-local:/root/.ollama"
        ports:
            - "11434:11434"
