services:

    ollama:
        container_name: ollama
        build: .
        # devices:
        #     - /dev/dri
        #     - /dev/kfd
        environment:
            - OLLAMA_DEBUG=1
            - STARTUP_PRELOAD=llama3.2
            - STARTUP_PULL=qwen2.5-coder:0.5b
        #     - HSA_OVERRIDE_GFX_VERSION=9.0.0
        #     - HSA_ENABLE_SDMA=0
        volumes:
            - "./data-local:/root/.ollama"
        ports:
            - "11434:11434"
